version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocritic
    - misspell
    - revive

  settings:
    revive:
      rules:
        - name: exported
          disabled: true
    gocritic:
      disabled-checks:
        - captLocal  # gopher-lua convention uses L for *lua.LState

issues:
  exclude-dirs:
    - vendor
